# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: download_era5

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: write

jobs:
  build_and_fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./task/.python-version"
      - name: Download era5
        env:
          GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
        run: |
          cd ./task
          uv sync
          uv run download_era5.py
      - name: Commit changes
        run: |
          git config --global user.email 1952620883@qq.com
          git config --global user.name hfdy
          git pull origin main
          git add shared/data_source/era5 shared/data_record.json shared/reconstruct shared/estimate
          git commit -m "download era5" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
