# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: download_geoscf

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: write

jobs:
  build_and_fetch_cnemc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          working-directory: ./task
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./task/.python-version"
      - name: download geoscf
        env:
          GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
        run: |
          cd ./task
          uv run download_geoscf.py
      - name: commit changes
        run: |
          git config --global user.email 1952620883@qq.com
          git config --global user.name hfdy
          git pull origin main
          git add shared/data_source/geoscf
          git commit -m "download geoscf" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
